### ISSUE TITLE
PHP7 Null class error

### ISSUE THREAD

**Issue by borantula** [felixwahner/TextformatterOEmbed#2]
Hello,

I got error from essence lib included in package. It uses classname Null in 2 places and PHP7 is throwing Cannot use 'Null' as class name as it is reserved error. I changed classname to NullLogger (and it's usages of course) and it is fixed. 
Didn't want to send a PR request as this look likes an included library and you may need to update it.

**Comment by felixwahner** [comment]
Hi @borantula - I've just pushed an update which adds the latest essence version with PHP7 support. Let me know if this works for you. Regarding the included library: As i didn't wanted to break backwards compatibility and processwire doesn't support composer in it's stable version yet I "did it again" and added the library to the repository. This will most propably be subject to change in the near future.
