### ISSUE TITLE
Error when applied to an empty field

### ISSUE THREAD

**Issue by MichaelvanLaar** [felixwahner/TextformatterOEmbed#3]
When the textformatter is applied to a field (using CKEditor in this example) and I leave this field empty on a specific page, this page cannot be rendered. Instead I get an error message, see example:

> Exception: Unable to load HTML document. (in /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/assets/cache/FileCompiler/site/modules/TextformatterOEmbed/vendor/essence/dom/src/Document/Native.php line 78)
> # 0 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/assets/cache/FileCompiler/site/modules/TextformatterOEmbed/vendor/essence/dom/src/Document/Native.php(38): Essence\Dom\Document\Native->_loadDocument()
> # 1 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/assets/cache/FileCompiler/site/modules/TextformatterOEmbed/vendor/essence/dom/src/Document/Factory/Native.php(23): Essence\Dom\Document\Native->__construct('')
> # 2 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/assets/cache/FileCompiler/site/modules/TextformatterOEmbed/vendor/essence/essence/lib/Essence/Crawler.php(72): Essence\Dom\Document\Factory\Native->document('')
> # 3 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/assets/cache/FileCompiler/site/modules/TextformatterOEmbed/vendor/essence/essence/lib/Essence/Essence.php(105): Essence\Crawler->crawl('')
> # 4 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/assets/cache/FileCompiler/site/modules/TextformatterOEmbed/TextformatterOEmbed.module(233): Essence\Essence->crawl('')
> # 5 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Textformatter.php(60): TextformatterOEmbed->format('')
> # 6 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/Fieldtype/FieldtypeText.module(94): ProcessWire\Textformatter->formatValue(Object(ProcessWire\Page), Object(ProcessWire\Field), '')
> # 7 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/Fieldtype/FieldtypeTextarea.module(119): ProcessWire\FieldtypeText->___formatValue(Object(ProcessWire\Page), Object(ProcessWire\Field), '')
> # 8 [internal function]: ProcessWire\FieldtypeTextarea->___formatValue(Object(ProcessWire\Page), Object(ProcessWire\Field), '')
> # 9 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(374): call_user_func_array(Array, Array)
> # 10 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/WireHooks.php(549): ProcessWire\Wire->_callMethod('___formatValue', Array)
> # 11 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(399): ProcessWire\WireHooks->runHooks(Object(ProcessWire\FieldtypeTextareaLanguage), 'formatValue', Array)
> # 12 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/LanguageSupport/FieldtypeTextareaLanguage.module(65): ProcessWire\Wire->__call('formatValue', Array)
> # 13 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/LanguageSupport/FieldtypeTextareaLanguage.module(65): ProcessWire\FieldtypeTextarea->formatValue(Object(ProcessWire\Page), Object(ProcessWire\Field), '')
> # 14 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Page.php(1265): ProcessWire\FieldtypeTextareaLanguage->formatValue(Object(ProcessWire\Page), Object(ProcessWire\Field), Object(ProcessWire\LanguagesPageFieldValue))
> # 15 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Page.php(996): ProcessWire\Page->getFieldValue('body')
> # 16 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Page.php(1431): ProcessWire\Page->get('body')
> # 17 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/site/templates/_init.php(21): ProcessWire\Page->__get('body')
> # 18 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/TemplateFile.php(255): require('/var/www/virtua...')
> # 19 [internal function]: ProcessWire\TemplateFile->___render()
> # 20 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(374): call_user_func_array(Array, Array)
> # 21 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/WireHooks.php(549): ProcessWire\Wire->_callMethod('___render', Array)
> # 22 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(399): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
> # 23 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/PageRender.module(512): ProcessWire\Wire->__call('render', Array)
> # 24 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/PageRender.module(512): ProcessWire\TemplateFile->render()
> # 25 [internal function]: ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
> # 26 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(374): call_user_func_array(Array, Array)
> # 27 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/WireHooks.php(549): ProcessWire\Wire->_callMethod('___renderPage', Array)
> # 28 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(399): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
> # 29 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/WireHooks.php(629): ProcessWire\Wire->__call('renderPage', Array)
> # 30 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/WireHooks.php(629): ProcessWire\PageRender->renderPage(Object(ProcessWire\HookEvent))
> # 31 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(399): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
> # 32 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/Process/ProcessPageView.module(205): ProcessWire\Wire->__call('render', Array)
> # 33 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/modules/Process/ProcessPageView.module(205): ProcessWire\Page->render()
> # 34 [internal function]: ProcessWire\ProcessPageView->___execute(true)
> # 35 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(374): call_user_func_array(Array, Array)
> # 36 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/WireHooks.php(549): ProcessWire\Wire->_callMethod('___execute', Array)
> # 37 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/wire/core/Wire.php(399): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
> # 38 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/index.php(55): ProcessWire\Wire->__call('execute', Array)
> # 39 /var/www/virtual/earlgrey/pwtest.dev.michaelvanlaar.com/index.php(55): ProcessWire\ProcessPageView->execute(true)
> # 40 {main}

**Comment by gmclelland** [comment]
I got errors as well when I view a page that has an empty field.  I wonder if this is because the external libraries are in the module's folder.  Maybe it is trying to use Processwire's File Complier on those libraries and it doesn't see the required namespace?

Maybe this module should not include the vendor folder and instead just provide instructions to download the third party libraries with composer?

If I remember correctly, the jumplinks module was facing the same problems when upgrading from 2.x to 3.x. see https://github.com/rockettpw/jumplinks/issues/14

> Composer (dependencies are installed via the global composer.json file and not packaged in the module itself)

**Comment by gmclelland** [comment]
Hmm... I don't think the File Complier is causing this error.  I moved this module's vendor directory to the root of my site and commented out the require_once... autoload.php 

The module now still works on some pages but doesn't work on pages with an empty field.

So I'm guessing the bug is in the .module itself?

**Comment by gmclelland** [comment]
Here is a little easier to read version of the error I got with the unaltered TextformatterOEmbed.
![2016-11-11 12-22-44](https://cloud.githubusercontent.com/assets/40570/20225559/a36737b0-a809-11e6-8cb0-a540de7b5708.jpg)

Here is the same error I got after moving the vendor directory to the site root.
![nati 2016-11-11 12-28-43](https://cloud.githubusercontent.com/assets/40570/20225738/8ecfd932-a80a-11e6-9c1c-eea5d41e5156.jpg)

**Comment by gmclelland** [comment]
Here is a pull request to fix these errors https://github.com/felixwahner/TextformatterOEmbed/pull/4

**Comment by felixwahner** [comment]
Thanks for contributing. This has been merged,
